name: set_value
description: Create nested values and any intermediaries using list notation ['a','b',c'] OR dot notation "a.b.c".
version: 1.0.2
homepage: https://github.com/Ferdzzzzzzzz/set_value

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  pretty_json:
